#!/usr/bin/env python3
"""Regenerate the Style matrix table in SKILL.md from config/style.json.

Usage:
    python3 generate_style_doc.py            # rewrite SKILL.md in place
    python3 generate_style_doc.py --check    # exit 1 if SKILL.md is out of date
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from text_to_docx import (  # noqa: E402
    STYLE_ENTRY_TO_GLOBAL_NAME,
    build_default_style_config,
    deep_merge_style_config,
    load_style_config_file,
    validate_style_config,
)

SCRIPT_DIR = Path(__file__).resolve().parent
SKILL_PATH = SCRIPT_DIR.parent / 'SKILL.md'
DEFAULT_CONFIG_PATH = SCRIPT_DIR.parent / 'config' / 'style.json'

START_MARKER = '<!-- STYLE_MATRIX_START: generated by scripts/generate_style_doc.py from config/style.json -->'
END_MARKER = '<!-- STYLE_MATRIX_END -->'

TABLE_HEADER = (
    '| Style | Font | Size (pt) | Color | Bold | Line spacing | Before (pt) | After (pt) | First-line chars | Alignment |\n'
    '|---|---|---:|---|---|---|---:|---:|---:|---|'
)


def resolve_effective_config(config_path: Path) -> dict:
    default = build_default_style_config()
    if not config_path.is_file():
        return default
    raw = load_style_config_file(config_path)
    validate_style_config(raw)
    return deep_merge_style_config(default, raw)


def format_number(value) -> str:
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value)


def render_table(config: dict) -> str:
    fonts = config.get('fonts', {})
    rows = [TABLE_HEADER]
    for entry_id in STYLE_ENTRY_TO_GLOBAL_NAME:
        entry = config['styles'][entry_id]
        font_name = fonts.get(entry.get('font'), entry.get('font'))
        color = entry.get('color') or '—'
        bold = 'yes' if entry.get('bold') else ('no' if entry.get('bold') is False else '—')
        rows.append(
            f"| {entry_id} | {font_name} | {format_number(entry['size_pt'])} | {color} | {bold} | "
            f"{entry['line_spacing']} | {format_number(entry['before_pt'])} | {format_number(entry['after_pt'])} | "
            f"{entry['first_line_chars']} | {entry['alignment']} |"
        )
    return '\n'.join(rows)


def build_new_skill_md(text: str, config: dict) -> str:
    try:
        start = text.index(START_MARKER)
        end = text.index(END_MARKER, start) + len(END_MARKER)
    except ValueError as exc:
        raise SystemExit(
            f'STYLE_MATRIX markers not found in {SKILL_PATH}; add {START_MARKER!r} and '
            f'{END_MARKER!r} around the table before running this script'
        ) from exc

    block = f'{START_MARKER}\n{render_table(config)}\n{END_MARKER}'
    return text[:start] + block + text[end:]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        '--config', default=str(DEFAULT_CONFIG_PATH),
        help='Style config to render (default: config/style.json, falling back to built-in defaults if absent)',
    )
    parser.add_argument('--check', action='store_true', help='Do not write; exit 1 if SKILL.md is out of date')
    args = parser.parse_args()

    config = resolve_effective_config(Path(args.config))
    current_text = SKILL_PATH.read_text(encoding='utf-8')
    new_text = build_new_skill_md(current_text, config)

    if args.check:
        if new_text != current_text:
            raise SystemExit(f'{SKILL_PATH} is out of date; run: python3 {Path(__file__).name}')
        print(f'{SKILL_PATH} is in sync with {args.config}')
        return

    if new_text == current_text:
        print(f'{SKILL_PATH} already in sync with {args.config}')
        return

    SKILL_PATH.write_text(new_text, encoding='utf-8')
    print(f'Regenerated {SKILL_PATH} style matrix from {args.config}')


if __name__ == '__main__':
    main()
